language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - cassandra

install: mvn compile

script: mvn test -Pcore-test,memory && mvn test -Pcore-test,cassandra && mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
